name: exception
description: A starting point for Dart libraries or applications.
version: 2.0.7
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  console:
    git: git@github.com:sky-train/console.git

dev_dependencies:
  lints: 4.0.0
  test: 1.25.7
