name: app_exception
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

dev_dependencies:
  lints: 2.1.1
  test: 1.24.4
